version: "3"
services:

  # Mariadb DataBase
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - vl_mariadb:/var/lib/mysql
    networks:
      - msaouab_net
    env_file:
      - .env

  # Nginx Web Server
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - vl_wp:/var/www/html
    ports:
      - "443:443"
    networks:
      - msaouab_net
    env_file:
      - .env
  
  # WordPress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    # restart: always
    depends_on:
      - mariadb
    volumes:
      - vl_wp:/var/www/html/
    networks:
      - msaouab_net
    env_file:
      - .env

networks:
  msaouab_net:

volumes: 
  vl_mariadb:
  vl_wp:
    driver_opts:
      type: none
      o: bind
      device: /home/msaouab/data